### ISSUE TITLE
Bug: Registration from the admin side is not working

### ISSUE THREAD

**Issue by abha224** [anitab-org/vms#1002]
## Description
As an admin I need to be able to register with the vms website, so that I can check on the volunteer's status. Currently, when an admin tries to register with vms, there is an error displayed.

## Mocks
![Screenshot from 2020-07-30 22-38-34](https://user-images.githubusercontent.com/39526159/88965344-b07e3580-d2bb-11ea-9ba3-eec44cd60766.png)

## Acceptance Criteria
The admin is successfully able to register with vms

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

**Comment by devkapilbansal** [comment]
Similar to #1087
