### ISSUE TITLE
UI: the country field in signup page has label "city"

### ISSUE THREAD

**Issue by rkpattnaik780** [anitab-org/vms#1023]
## Description
As a new volunteer,
I need provide my address,
so that I can register myself in the vms.

## Mocks
![Screenshot from 2020-08-22 01-20-03](https://user-images.githubusercontent.com/23582438/90929074-aa402c80-e415-11ea-939b-a488d5cc1a85.png)

### Update [Required]
- [ ] Fixed sign up form

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by priyanshurohilla** [comment]
Can i work on this?

**Comment by rkpattnaik780** [comment]
@priyanshurohilla since the issue is labelled Open Source Hack, it is not up for grab currently. Any PR for this tag should be raised after 1st september, i.e after commencement of OSH.

**Comment by priyanshurohilla** [comment]
@rkpattnaik780  yes i am participating in it. But can you tell me will it be starting from 1st september 00:00 IST?

**Comment by yash2189** [comment]
Can I work on this issue @rkpattnaik780 ?

**Comment by rkpattnaik780** [comment]
This issue is specific to OSH. If you are an OSH participant, feel free to claim this issue on September 1 and I will assign it to you. I can assign it to you now if you are not looking forward to participate in OSH.

**Comment by yash2189** [comment]
Can I work on this @rkpattnaik780 ?

**Comment by Abhijit5463** [comment]
Hey I am new in this community and I am participating in OSH can I take this up?

**Comment by decon-harsh** [comment]
I am participating in OSH and I would like to work on this !

**Comment by utkzas** [comment]
hey can this issue be assigned to me?

**Comment by rkpattnaik780** [comment]
Assigning it to @decon-harsh . @yash2189 @Abhijit5463 you already have been assigned issues in vms. @utkzas since it is first come first serve, I can't assign it to you. Please browse through other unassigned issues :).

**Comment by yash2189** [comment]
Can I work on this now please since I have no other issues assigned to me.

**Comment by rkpattnaik780** [comment]
> Can I work on this now please since I have no other issues assigned to me.

This issue already has a PR open for it, please browse through other issues.
