### ISSUE TITLE
UI[Bug]: The home page UI distorted for small screens

### ISSUE THREAD

**Issue by Kajol-Kumari** [anitab-org/vms#1024]
## Description
The menu option of `signup`, `login` etc gets distorted for smaller and xs-screens.

## Mocks
![imageedit_1_9024988642](https://user-images.githubusercontent.com/44888949/90972685-f20ba480-e538-11ea-95da-67d2261fd17d.png)

### Update [Required]
- [ ] Fix UI of home page for small screen

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by Sommie09** [comment]
Could I work on this issue?
I'm participating in OSH

**Comment by adsv1623** [comment]
Could I work on this ? It will be great to get started with this.

**Comment by Kajol-Kumari** [comment]
@Sommie09  @adsv1623 It's good to see you guys are interested in taking up this issue. But all the issues with the label of `open source hack` will be assigned to the `OSH` participants starting from 1st of september on the basis of First come first serve so please wait patiently till 1st of september and till then you can set up the repo. locally and get acquainted with the project functionalities and its codebase.

**Comment by SanketDG** [comment]
This is slightly related/almost a duplicate of #161

**Comment by Kajol-Kumari** [comment]
@SanketDG If we talk about #161 it's going to be a huge if we add responsiveness of the whole site in a single PR. So we can consider it's to be a subpart.

**Comment by SanketDG** [comment]
Makes sense, let's try to break #161 into several subparts.

CC @gaurivn who labelled the other issue

**Comment by Kajol-Kumari** [comment]
Hey Everybody, all who are interested in this issue. Please accept my apologies but according to the new guidelines we received, we will count `First come first serve` on the basis of comments/claims done 1st september onwards. So, everyone who are interested in this issue, do come again on 1st and comment first to get this issue assigned to you.

**Comment by titiksha01** [comment]
@Kajol-Kumari Hello, I would like to work on this issue as part of OSH. Can I be assigned this issue? Thank You

**Comment by Aaishpra** [comment]
@Kajol-Kumari can i work on this

**Comment by Kajol-Kumari** [comment]
Hey @titiksha01 please go ahead with this issue. @Aaishpra as we are following `FCFS` so can't assign this issue to you, feel free to take any other issue.

**Comment by titiksha01** [comment]
@Kajol-Kumari Thank you for the opportunity

**Comment by titiksha01** [comment]
@Kajol-Kumari I had a doubt regarding this. To check the changes i have made it on the the UI, do I need to run it on docker? because the html file won't open properly in my browser i.e the css and js characteristics are not visible as they are visible on the link provided in the repo for the volunteer management system home page.

I am new to this community and open source so please guide me with this so that I check if my changes fixed the Bug in UI. Thank you

**Comment by SanketDG** [comment]
@titiksha01 You will have to run the application as mentioned in the [setup](https://github.com/anitab-org/vms/blob/develop/aut_docs/Installation_Setup.md) docs, did you manage to follow them through?

**Comment by titiksha01** [comment]
@SanketDG  I was following it... i am facing an error when i used  
`python manage.py makemigrations auth volunteer administrator organization event job shift registration `
in Linux WSL.
`python: can't open file 'manage.py': [Errno 2] No such file or directory`

**Comment by Kajol-Kumari** [comment]
> @SanketDG I was following it... i am facing an error when i used
> `python manage.py makemigrations auth volunteer administrator organization event job shift registration `
> in Linux WSL.
> `Traceback (most recent call last): File "manage.py", line 8, in <module> from django.core.management import execute_from_command_line ImportError: No module named django.core.management`
> Pls help me with this.

@titiksha01 this error is because you are runing the command in the wrong directory. You must be in `/vms/vms` (the directory that contains the `manage.py`) and then run this command.

**Comment by titiksha01** [comment]
@Kajol-Kumari Yes, Thank You... I was able to set up and run the server

**Comment by titiksha01** [comment]
![home](https://user-images.githubusercontent.com/57208352/92305922-4a1ac000-efa9-11ea-93f9-0503140f8d4d.JPG)
  @Kajol-Kumari Its displaying correctly when i run the server.

**Comment by Kajol-Kumari** [comment]
@titiksha01 can you please check for the other pages? If the UI is fine for mobile view?

**Comment by titiksha01** [comment]
@Kajol-Kumari It is correct in the sign-in, sign up and signup admin pages as well. 
Do i need to sign up and check the the UI?

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari It is correct in the sign-in, sign up and signup admin pages as well.
> Do i need to sign up and check the the UI?

@titiksha01 yes, as we want to make the whole site small device compatible in this issue.

**Comment by titiksha01** [comment]
@Kajol-Kumari Current UI for small devices is correct in upcoming shifts, completed shifts, shift sign up, report and profile pages as well. 
![a](https://user-images.githubusercontent.com/57208352/92491590-07a6ec80-f210-11ea-9003-9f1c558d52b8.JPG)

**Comment by Kajol-Kumari** [comment]
@titiksha01 thank you for letting me know this. I think this issue has been resolved so i would reccomend you to take any other issue or else check if the UI is fine for other screens sizes and work on it.

**Comment by SanketDG** [comment]
Close this then?

Although I'd be very curious to know why the UI doesn't seem right on your side.

**Comment by Kajol-Kumari** [comment]
@SanketDG probably i missed testing it on my local as i was expecting the live url to work fine.

**Comment by titiksha01** [comment]
@Kajol-Kumari  Okay, I will search for some other issue
