### ISSUE TITLE
[Documentation] Separate feature and bug template

### ISSUE THREAD

**Issue by Kajol-Kumari** [anitab-org/vms#1026]
## Description
Currently we have a single issue template for both `feature` and `bug` issues

### Update 
- [ ] Create separate template for `feature` request and `bug` report.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
.5 hours

**Comment by priyanshurohilla** [comment]
Can i work on this?

**Comment by Kajol-Kumari** [comment]
@priyanshurohilla It's good to see you are interested in taking up this issue. But all the issues with the label of `open source hack` will be assigned to the `OSH` participants starting from 1st of september on the basis of `First come first serve` basis so please wait patiently till 1st of september.

**Comment by vaibhavarora102** [comment]
@Kajol-Kumari I am interested for working on this
thanks!

**Comment by Kajol-Kumari** [comment]
Hey Everybody, all who are interested in this issue. Please accept my apologies but according to the new guidelines we received, we will count `First come first serve` on the basis of comments/claims done 1st september onwards. So, everyone who are interested in this issue, do come again on 1st and comment first to get assigned.

**Comment by vaibhavarora102** [comment]
Hi, can you pls assign this issue to me as its already 1st of September and I guess OSH has started
Thanks

**Comment by Abjcodes** [comment]
I would like to work on this issue as a part of OSH. Can you assign me this issue? Thank You.

**Comment by Kajol-Kumari** [comment]
Hey @vaibhavarora102 as I have assigned you one issue already so acn't assign you anymore till you open up a valid PR for the same. 
@Abjcodes please go ahead with this issue :+1:

**Comment by Abjcodes** [comment]
@Kajol-Kumari I have send a pull request. Kindly review it.

**Comment by vaibhavarora102** [comment]
I had also sent a pull request 
can you pls assign me to know as I had come first (12:02 a.m)
thanks

**Comment by Kajol-Kumari** [comment]
Hey @vaibhavarora102 please don't continue working on any issue untill it gets assigned to you. Also as i had previously mentioned as well, you already have one issue assigned to you, so i request you to please close your PR For this issue and work on the assigned issue.

@Abjcodes thanks for opening the PR, i will review it ASAP.

**Comment by vaibhavarora102** [comment]
I don't had opened any PR for this 

Kindly check

**Comment by Kajol-Kumari** [comment]
Hey @vaibhavarora102, I apologize for misunderstanding what you said but please understand that if someone is already assigned an issue, we can't assign it to you unless the issue requires multiple assignees(which isn't the case here) so please feel free to claim some unassigned issue.

**Comment by vaibhavarora102** [comment]
Okay thanks
