### ISSUE TITLE
Add installation steps for Django

### ISSUE THREAD

**Issue by Ajitesh13** [anitab-org/vms#1032]
## Description
As a new contributor, It would be good if We have a installation guide on Django. Currently we have docker setup instruction. But it would be good if readily instructions are available for downloading, this will make the process fast.

### Update [Required]
- [ ] Add some instructions for django installation

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by BALaka-18** [comment]
Hi @Ajitesh13, can I work on this issue ? I am participating in OSH.

**Comment by Ajitesh13** [comment]
Hey! That's great, however, OSH starts on 1st September and I can't officially assign you just yet. Your PR will be considered for OSH only if you're assigned after 1st. Before that, if I assign you it'll be a regular contribution.

If you want to participate in OSH specifically, I'd suggest you set up all the projects that you're interested to work on first. And meanwhile, you can also work on other issues not labeled "Open Source Hack", because any contribution is good for us!

Do come back on 1st and I'll happily assign you to this issue and your contribution will count in OSH!

**Comment by SanketDG** [comment]
Is this not enough https://github.com/anitab-org/vms/blob/develop/aut_docs/Installation_Setup.md @Ajitesh13 ?

We can definitely want to move this to the README

**Comment by nitish-awasthi** [comment]
Hi! @Ajitesh13  can I work on this issue for OSH?

**Comment by Ajitesh13** [comment]
@SanketDG from a new comer perspective I think it would be better to move it to the README

**Comment by SanketDG** [comment]
Feel free to adjust the issue then.

**Comment by Ajitesh13** [comment]
@SanketDG Can you have a look at my issue in the brainstorming doc, under documentation section. I have raised a potential issue with the commands of "python3.6", in the installation guide. Can you give your views on that. This issue is dependent on that.

**Comment by SanketDG** [comment]
> In the installation, its mentioned that python3.6 should be installed in all commands, if possible replace it with python3 

Makes sense to me, I'd ideally also label it as First Timers Only

**Comment by yash2189** [comment]
can I work on this issue in OSH @SanketDG ?

**Comment by BALaka-18** [comment]
Hi @Ajitesh13 , I would like to work on this issue

**Comment by Abjcodes** [comment]
I would like to work on this issue as a part of OSH. Can you assign me this issue? Thank You.

**Comment by Ajitesh13** [comment]
Hello Guys, thanks for your interest in this issue, As we have to planned to move in a FCFS basis, I have to assign this bug to @yash2189 . If at some point of time, he will fail to meet the requirements, then I will assign this issue to one among you.

**Comment by yash2189** [comment]
Hello @Ajitesh13  I have created a PR. Please review the same. Thanks.

**Comment by ashwinitanpure** [comment]
@Ajitesh13 I would like to work on this

**Comment by 96RadhikaJadhav** [comment]
I would like to work on this issue as a part of OSH. Could you please assign me this issue? I'm a first time contributor.

**Comment by yash2189** [comment]
@Ajitesh13  Please review my PR

**Comment by Ajitesh13** [comment]
OK, @yash2189 sorry for the delay, I will review the PR now

**Comment by singhanurag05** [comment]
Is this available to work on? I am a first time contributor.

**Comment by trivediavinash** [comment]
Can i work on it ,i am a first time contributor

**Comment by Anmollenka** [comment]
I will like to work on this issue.Can you please assign it to me when it is free??

**Comment by yash2189** [comment]
> OK, @yash2189 sorry for the delay, I will review the PR now

Any updates @Ajitesh13? should I make any changes to the existing PR that I made yesterday?

**Comment by SanketDG** [comment]
@Ajitesh13 I am not sure if this is an helpful issue at all, feel free to close this.

**Comment by Ajitesh13** [comment]
Ok, @SanketDG Thanks for your insights, I am closing this issue.
