### ISSUE TITLE
Add installation steps for docker 

### ISSUE THREAD

**Issue by Ajitesh13** [anitab-org/vms#1033]
## Description
As a beginner I expect all the instructions are given to me are complete in all respect. Currently in the README.md or in installation setup there is no instructions in downloading docker.

### Update [Required]
- [ ] [Add docker installation guide]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1-1.5 hours

**Comment by ankita1964** [comment]
Hey @Ajitesh13 I would like to work on this issue.

**Comment by ankita1964** [comment]
Do we need to register also?

**Comment by Ajitesh13** [comment]
Hey! That's great, however, OSH starts on 1st September and I can't officially assign you just yet. Your PR will be considered for OSH only if you're assigned after 1st. Before that, if I assign you it'll be a regular contribution.

If you want to participate in OSH specifically, I'd suggest you set up all the projects that you're interested to work on first. And meanwhile, you can also work on other issues not labeled "Open Source Hack", because any contribution is good for us!

Do come back on 1st and I'll happily assign you to this issue and your contribution will count in OSH!

**Comment by SanketDG** [comment]
There are a bunch of guides that explain how to install Docker, I don't see how ours could be different. Infact by doing something that's already been covered "officially", we risk assisting the contributor into doing something wrong because we forgot something.

**Comment by nitish-awasthi** [comment]
Hey @Ajitesh13 I would like to work on this issue for OSH.

**Comment by Ajitesh13** [comment]
@SanketDG I think you are right. But what do you think, if we just add the official docker installation link before the instructions to setup the docker(in the README) ?

**Comment by Ajitesh13** [comment]
@SanketDG I check thoroughly now, I think, all the requirements has already been fulfilled, which I was intending in the readme. I feel there is no need for the issue, we may close this.

**Comment by Abjcodes** [comment]
I would like to work on this issue as a part of OSH. Can you assign me this issue? Thank You.
