### ISSUE TITLE
Add installation steps for Windows OS

### ISSUE THREAD

**Issue by keshakaneria** [anitab-org/vms#1036]
## Description
Currently, the installation steps are given for Linux OS. Add installation steps along with their codes in [Installation guide](https://github.com/anitab-org/vms/blob/develop/aut_docs/Installation_Setup.md) for Windows OS.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by ashwinijha6** [comment]
Hey Hi @keshakaneria I would like to work on this issue

**Comment by keshakaneria** [comment]
@ashwinijha6 I am glad that you want to contribute! This issue is under Open source Hack event which will be started from 1st Sept., 2020. I request you to wait until then and will assign you once the event is started so that you can also contribute in the event as participant. :)

**Comment by ankita1964** [comment]
Hey @keshakaneria I would like to work on this issue! It really seems interesting. Can you please guide me through?

**Comment by ashwinijha6** [comment]
Thanku @keshakaneria 
I'll be participating in the OSH event.

**Comment by keshakaneria** [comment]
@ankita1964 You might also participate in OSH event from 1st Sept. Once it starts, I'll assign you guys first come first serve. Till then, you can go through the codebase and be ready with locally installing it in your workspace :)

**Comment by ankita1964** [comment]
Okay! Thanks. Can one task be assigned to one person only?

**Comment by keshakaneria** [comment]
Yes, single issue will be assigned to a single person for the 3 days to work on.

**Comment by ankita1964** [comment]
What will be the criteria for selection?

**Comment by keshakaneria** [comment]
There are no selection criteria. Anyone can apply. You can follow this site for more information about the event https://anitab-org.github.io/events/open-source-hack/

**Comment by ankita1964** [comment]
Thanks for sharing the link. I meant who will get the chance to work on a
certain problem will be based upon what fact? First come first basis kinda?
Sorry for such queries😅...but I am really excited for it.

**Comment by keshakaneria** [comment]
First come first serve

**Comment by ashwinijha6** [comment]
@keshakaneria can I use the lastest version of python (Python 3.8.5) for the installation?

**Comment by keshakaneria** [comment]
@ashwinijha6 The requirements.txt file will have a fixed version, so i suppose we are not supposed to alter the version, rather just add the steps which uses current installation process.

**Comment by ashwinijha6** [comment]
ok

**Comment by ashwinijha6** [comment]
I had a doubt related to creating migrations for the database. When I'm following the steps in the installation guide:
  **python manage.py makemigrations auth volunteer administrator organization event job shift registration**
I'm getting an error module decouple not found
I have installed the module but I get this error
![error](https://user-images.githubusercontent.com/45794450/91457004-86f80000-e8a1-11ea-94f5-d62989a61e41.JPG)

**Comment by ashwinijha6** [comment]
export DJANGO_SECRET_KEY='foobarbaz'
What is this secret key do we have to make a .env file?

**Comment by SanketDG** [comment]
Yes, as instructed.

Put anything in the SECRET_KEY, does not matter for now.

**Comment by nitish-awasthi** [comment]
Hi @keshakaneria  I would like to work on this issue

**Comment by ashwinijha6** [comment]
Ya got it @SanketDG & @keshakaneria  there was a .env.example file present just created a .env file with the SECRET_KEY value, now I can create migrations for the database. Thanku :)

**Comment by keshakaneria** [comment]
@nitish-awasthi It is issued for OSH event on the basis of first come first serve basis. If someone's not working on it, the next interested person will be assigned to work on :)

**Comment by ashwinijha6** [comment]
@keshakaneria do we need to use the specified version of geckodriver, selenium & firefox ?
Because the installation guide says to use geckodriver version 0.20.1 but the setup-geckodriver.sh has version v0.26.0

**Comment by ashwinijha6** [comment]
Actually I know we are not suppose to change the version but for **pip install -r requirements.txt**  I'm getting an error for psycopg2 & selenium (shown below) that's why I just install it separately that is psycopg2-binary
![error1](https://user-images.githubusercontent.com/45794450/91537680-5319ea80-e934-11ea-98aa-1dbefdbb2a0b.JPG)

**Comment by ashwinijha6** [comment]
Do all the automated tests need to pass?
I'm getting certain errors  this is one of them

![error2](https://user-images.githubusercontent.com/45794450/91556837-0395e780-e951-11ea-8660-40936cdf702c.JPG)

**Comment by SanketDG** [comment]
@ashwinijha6 I am not sure which one of these comments is your exact problem, but feel free to post about your current problem on Zulip. Let's not pollute this space anymore, and keep it open for discussion regarding the issue.

**Comment by ashwinijha6** [comment]
ok sure @SanketDG

**Comment by saideepesh000** [comment]
#OSH, can I work on this.

**Comment by ashwinijha6** [comment]
@keshakaneria I would like to work on this issue as an OSH participant

**Comment by Abjcodes** [comment]
I would like to work on this issue as a part of OSH. Can you assign me this issue? Thank You.

**Comment by vanditkhurana** [comment]
I would like to work on this. Please assign me this issue.

**Comment by keshakaneria** [comment]
The assignment will be based on First Come First Serve. In case of any inactivity for 3 days, the next interested person will be assigned the issue.

**Comment by saideepesh000** [comment]
@keshakaneria, Actually I commented first, xD.

**Comment by keshakaneria** [comment]
@saideepesh000 you have already been assigned one issue. So, no more than one issues are to be assigned for a single person :)

**Comment by Anmollenka** [comment]
Can I work on this issue as a part of OSH??Thank You

**Comment by ashwinijha6** [comment]
@keshakaneria pls review my pull request #1081 & let me know the changes.

**Comment by Aaditree** [comment]
I wish to work on this issue. Please assign it to me.

**Comment by keshakaneria** [comment]
> I wish to work on this issue. Please assign it to me.

PR has already been opened for this issue and it is resolved. Thank you for your interest. You are welcomed to have a look at other issues available :)
