### ISSUE TITLE
Add the newcomers link of zulip chat for beginners 

### ISSUE THREAD

**Issue by Ajitesh13** [anitab-org/vms#1039]
## Description
For a beginner, along with the channel of #vms we should also add the channel link of #newcomers in README.md, this would make the process a little fast forward for the beginners to communicate with community members and solve their beginner-specific issues.

### Update [Required]
- [ ] [Add the link of #newcomers from anitab-org.zulipchat.com]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by Aaishpra** [comment]
@Ajitesh13 can i work on this

**Comment by Ajitesh13** [comment]
Hey! That's great, however, OSH starts on 1st September and I can't officially assign you just yet. Your PR will be considered for OSH only if you're assigned after 1st. Before that, if I assign you it'll be a regular contribution.

If you want to participate in OSH specifically, I'd suggest you set up all the projects that you're interested to work on first. And meanwhile, you can also work on other issues not labeled "Open Source Hack", because any contribution is good for us!

Do come back on 1st and I'll happily assign you to this issue and your contribution will count in OSH!

**Comment by Aaishpra** [comment]
Yeah ! Sure

**Comment by ankita1964** [comment]
Hey @Ajitesh13 I would really like to work on this issue. Can you please help?

**Comment by Ajitesh13** [comment]
Thanks for your interest in working in this issue. But please go through the above conversation, as this is a OSH marked issue. We can assign you the issue once the OSH period starts(after 1 sept). And meanwhile, you can also work on other issues not labeled "Open Source Hack", because any contribution is good for us!

Do come back on 1st and I'll happily assign you to this issue and your contribution will count in OSH!

**Comment by vaibhavarora102** [comment]
hi @Ajitesh13 , will it start from midnight 1 sept or any other time
kindly guide
thanks

**Comment by nitish-awasthi** [comment]
Hey @Ajitesh13 I would really like to work on this issue for OSH.

**Comment by Ajitesh13** [comment]
> hi @Ajitesh13 , will it start from midnight 1 sept or any other time
> kindly guide
> thanks

@vaibhavarora102 OSH will start from 1 sept midnight. For more information about the program you can move into our zulip chat and feel free to ask more questions.

**Comment by Abhijit5463** [comment]
Hey I am new in this community and I am participating in OSH can I take this up?

**Comment by vaibhavarora102** [comment]
Hi, can you pls assign this issue to me as its already 1st of September and I guess OSH has started
Thanks

**Comment by Ajitesh13** [comment]
Thanks for taking interest in this issue. As we go in FCFS basis, I have to first assign this bug to @Abhijit5463. If at some point he failed to meet the requirements, I will assign you this bug.

**Comment by 96RadhikaJadhav** [comment]
I would like to work on this issue as a part of OSH. Could you please assign me this issue? I'm a first time contributor.

**Comment by anishghimire603** [comment]
@Ajitesh13  can you please assign this to me I will be marked as contributed to documentation after contributing to this because I have contributed to QR or code and UI in mentorship-backend project.

**Comment by Ajitesh13** [comment]
As we have not heard from @Abhijit5463 for 2 days, I am unassigning this bug and opening it for other contributors.

**Comment by Ajitesh13** [comment]
I have assigned this issue to @vaibhavarora102 please go ahead and submit a PR and if you need any help, feel free to ask.

**Comment by vaibhavarora102** [comment]
thanks, I will do it at the earliest

**Comment by vaibhavarora102** [comment]
@Ajitesh13 kindly check I had made pr

**Comment by vaibhavarora102** [comment]
@Ajitesh13 there were certain commits in my main branch so I created new branch and then commit to del all those changes and after that did required changes and opened a pull request

**Comment by vaibhavarora102** [comment]
I am facing some problems in squashing and pushing back
but hopefully will solve issues by today's day end
thanks

**Comment by vaibhavarora102** [comment]
@Ajitesh13  sry for all that mess  in PR's
kindly accept the final one
