### ISSUE TITLE
Dropdown not visible in admin profile

### ISSUE THREAD

**Issue by sanchibansal340** [anitab-org/vms#1045]
## Description
As a user, I need to change the positioning of the dropdown in the admin profile, so that it is completely visible in small screen devices as well.

## Mocks

![Appearance in small screen devices](https://user-images.githubusercontent.com/51092036/91563631-d18a8280-e95c-11ea-8230-26ee98653782.png)

![Appearance in large-screen devices](https://user-images.githubusercontent.com/51092036/91563372-5923c180-e95c-11ea-94d2-cd824024d2fc.png)

### Update [Required]
- [ ] Screenshot with the updated design

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours 

## Note
The issue won't be available till September 1, 2020

**Comment by raniyer** [comment]
Hey, I'd like to work on this issue

**Comment by sanchibansal340** [comment]
Comment on 1st September and I will assign it to you.

**Comment by ooyeraju** [comment]
Hey, I would like to work on this. Participating in OSH

**Comment by sanchibansal340** [comment]
@ooyeraju I am assigning this to you

**Comment by decon-harsh** [comment]
Next in the queue!

**Comment by Tushika25** [comment]
I would like to work on this issue. Thank You!!!

**Comment by arjungarg07** [comment]
@sanchibansal340 Hey I am new in this community and I am participating in OSH can I take this up? ThankYou

**Comment by khushishikhu** [comment]
may i work on this issue?

**Comment by yash2189** [comment]
May I work on this issue? As of now I have completed my previous issue assigned to me.

**Comment by sanchibansal340** [comment]
@ooyeraju What's the update on this issue?

**Comment by ooyeraju** [comment]
I'm working on it.

**Comment by sanchibansal340** [comment]
@ooyeraju Any updates?

**Comment by psingh587** [comment]
Can I work on this? @sanchibansal340

**Comment by sanchibansal340** [comment]
@decon-harsh Are you willing to working on this issue?

**Comment by decon-harsh** [comment]
> @decon-harsh Are you willing to working on this issue?

Sure

**Comment by sujal111** [comment]
I am willing to work and solve this issue. Please assign me the same

**Comment by decon-harsh** [comment]
@sanchibansal340 Can I open a PR?

**Comment by sanchibansal340** [comment]
@decon-harsh Sorry for missing your comment. Please go ahead with the PR. Thanks :)
