### ISSUE TITLE
Logo distorted in small screen

### ISSUE THREAD

**Issue by sanchibansal340** [anitab-org/vms#1046]
## Description
As a user, I need to change the size of the logo in all pages, so that it is completely visible in small screen devices as well.

## Mocks

![Logo gets distorted](https://user-images.githubusercontent.com/51092036/91572336-3695a680-e964-11ea-9162-8b988fa309dc.png)

### Update [Required]
- [ ] Screenshot with the updated design

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours 

## Note
The issue will be available only from September 1, 2020

**Comment by harsh-9in** [comment]
hey @sanchibansal340, Can I work on this issue?

**Comment by sanchibansal340** [comment]
Comment on 1st September and I will assign it to you.

**Comment by saideepesh000** [comment]
#OSH, Can I work on it.

**Comment by saideepesh000** [comment]
#OSH, Can I work on it.

**Comment by titiksha01** [comment]
Hello, I would like to work on this issue as a part of OSH. Can you assign it to me?

**Comment by ymaheshwari1** [comment]
I am interested

**Comment by sanchibansal340** [comment]
@ymaheshwari1 I am assigning this to you as this is a first-timers issue.

**Comment by ymaheshwari1** [comment]
@sanchibansal340 The logo is looking fine on the mobile screens.

**Comment by sanchibansal340** [comment]
It was not working for my mobile screen previously. Thank you for updating about this @ymaheshwari1. I will look into this

**Comment by sanchibansal340** [comment]
@khushishikhu I faced some problems with the logo on my screen but it looks fine now. I will be closing the issue.
