### ISSUE TITLE
Create a code_of_conduct.md file

### ISSUE THREAD

**Issue by sanchibansal340** [anitab-org/vms#1047]
## Description
As a contributor, I need to modify the Code of Conduct, so that I understand about the organisation better and don't do something that breaches that code of conduct accidently.
1. The content should be consistent with [Code of Conduct here](https://github.com/anitab-org/documentation/blob/master/Contributing/CODE_OF_CONDUCT.md)
2. And then update the code of conduct link in **Readme.md**>>Contributing section as well as in **Contributing.md**.
3. Add the updated Code of Conduct file to doc folder.

## Acceptance Criteria
- [ ] Update [Required]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
30 minutes

## Note
This issue will be assigned from September 1, 2020

**Comment by atharwa-24** [comment]
I would like to work on this issue

**Comment by rutujadhanawade** [comment]
I would like to work on this..

**Comment by sanchibansal340** [comment]
Comment on 1st September and I will assign it to you.

**Comment by aniketrb-github** [comment]
@sanchibansal340, Can you please assign me this. Thanks. (I'm not an OSH participant but a first-time open source contributor)

**Comment by yash2189** [comment]
Can I work on this @sanchibansal340 ?

**Comment by Abjcodes** [comment]
I would like to work on this issue as a part of OSH. Can you assign me this issue?

**Comment by bhumikasharma29** [comment]
Please assign this to me.

**Comment by atharwa-24** [comment]
@sanchibansal340 I want to work on this!

**Comment by vanditkhurana** [comment]
I would like to work on this @sanchibansal340. Please assign me this issue.

**Comment by sanchibansal340** [comment]
I am assigning this to you @aniketrb-github

**Comment by utkzas** [comment]
hey can this issue be assigned to me?

**Comment by sanchibansal340** [comment]
@aniketrb-github I have assigned this issue to you.

**Comment by sujal111** [comment]
I am willing to work and solve this issue. Please assign me the same

**Comment by aniketrb-github** [comment]
> I am willing to work and solve this issue. Please assign me the same

Hi @sujal111 
This issue is already been assigned, has been reviewed and approved for merge. 
Please feel free to view other issues in the issue list. Thanks. :)

**Comment by sujal111** [comment]
🤔🤔🤔🙄🙄🙄okay
