### ISSUE TITLE
Create a reporting_guidelines.md

### ISSUE THREAD

**Issue by sanchibansal340** [anitab-org/vms#1048]
## Description
As a user, I need to modify the reporting guidelines, so that I can seek for help when necessary.
1. The content should be consistent with [Reporting Guidelines](https://github.com/anitab-org/mentorship-flutter/blob/develop/.github/reporting_guidelines.md)
2. And then update the code of conduct link in **Readme.md**>>Contributing section.
3. Add the updated Reporting Guidelines file to doc folder.

## Acceptance Criteria
- [ ] Update [Required]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
30 minutes

## Note
This issue will be assigned from September 1, 2020

**Comment by vj-codes** [comment]
@sanchibansal340 I would like to work on this for OSH:)

**Comment by sanchibansal340** [comment]
Comment back on 1st September and I will assign you this issue :)

**Comment by sanchibansal340** [comment]
Comment on 1st September and I will assign it to you :)

**Comment by aniketrb-github** [comment]
@sanchibansal340, Can you please assign me this. Thanks. (I'm not an OSH participant but a first-time open source contributor)

**Comment by Abjcodes** [comment]
I would like to work on this issue as a part of OSH. Can you assign me this issue? Thank You.

**Comment by vj-codes** [comment]
@sanchibansal340 I would like to work on this after your reference in 1st comment here

**Comment by sanchibansal340** [comment]
I am assigning this to you @aniketrb-github

**Comment by sanchibansal340** [comment]
@aniketrb-github I have assigned you another issue.
@Abjcodes This is a first-timer only and you have been assigned another issue

**Comment by aniketrb-github** [comment]
> @aniketrb-github I have assigned you another issue.
> @Abjcodes This is a first-timer only and you have been assigned another issue

Sure @sanchibansal340, 
Then can you assign me #1047 at least? I have commented on #1047 as you've told us for the FCFS basis. :)

**Comment by 96RadhikaJadhav** [comment]
I would like to work on this issue as a part of OSH. Could you please assign me this issue? I'm a first time contributor.

**Comment by smart-girll** [comment]
I would like to work on this issue as a part of OSH. Could you please assign this issue? I am a first time contributor
