### ISSUE TITLE
Add installation guide for RHEL/Fedora

### ISSUE THREAD

**Issue by rkpattnaik780** [anitab-org/vms#1051]
## Description

The installation guide currently has instructions for Ubuntu. Add the steps to be followed while setting up VMS in RHEL/Fedora to the [installation guide](https://github.com/anitab-org/vms/blob/develop/aut_docs/Installation_Setup.md).

### Update [Required]
- [ ] A section in the installation guide to setup the project in RHEL/Fedora.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by khushishikhu** [comment]
may i take this issue?

**Comment by rkpattnaik780** [comment]
Hello @khushishikhu . Thanks for showing interest towards contributing this project. You can't be assigned this issue right now, please claim it earliest after 1st Sept(commencement of OSH).

**Comment by khushishikhu** [comment]
can i take this issue

**Comment by Abjcodes** [comment]
I would like to work on this issue as a part of OSH. Can you assign me this issue? Thank You.

**Comment by rkpattnaik780** [comment]
Go ahead @khushishikhu. Feel free to reach out if stuck anywhere.

> can i take this issue

**Comment by rkpattnaik780** [comment]
> I would like to work on this issue as a part of OSH. Can you assign me this issue? Thank You.

Hello! Thanks for showing interest towards this issue however the issue had to be assigned based on first come first serve basis. Feel free to browse through other issues.

**Comment by khushishikhu** [comment]
@rkpattnaik780  the installation guide is for RHEL 8 or any other version

**Comment by 96RadhikaJadhav** [comment]
I would like to work on this issue as a part of OSH. Could you assign me this issue? I'm a first time contributor.

**Comment by rkpattnaik780** [comment]
> @rkpattnaik780 the installation guide is for RHEL 8 or any other version

RHEL 8. I would be reviewing your PR by EOD.

**Comment by sujal111** [comment]
_I am willing to work and solve this issue. Please assign me the same_
