### ISSUE TITLE
Add a badge for Python version in README.md

### ISSUE THREAD

**Issue by rkpattnaik780** [anitab-org/vms#1052]
## Description
README.md should have a badge for denoting the version of python needed.

## Mocks
README of [mentorship-backend](https://github.com/anitab-org/mentorship-backend/blob/develop/README.md).

![Screenshot from 2020-08-29 20-56-52](https://user-images.githubusercontent.com/23582438/91640313-41bb0600-ea3a-11ea-8ab6-470ba7b1c94e.png)

## Definition of Done
- [ ] Badge should be added with appropriate version.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by atharwa-24** [comment]
I would like to work on this one!!! ~OSH

**Comment by bhumikasharma29** [comment]
I want to work on this!

**Comment by aniketrb-github** [comment]
@rkpattnaik780, Can you please assign me this. Thanks.

**Comment by rkpattnaik780** [comment]
Hello everyone! Thanks for showing interest in this issue. If you are looking forward to participate in OSH. Please feel free to claim this issue after 1st September (commencement of OSH program).

**Comment by aniketrb-github** [comment]
@rkpattnaik780, Can you please assign me this. Thanks. (I'm not an OSH participant but a first-time open source contributor)

**Comment by yash2189** [comment]
Can I work on this @rkpattnaik780 ?

**Comment by atharwa-24** [comment]
I had fixed this one

**Comment by Abjcodes** [comment]
I would like to work on this issue as a part of OSH. Can you assign me this issue? Thank You.

**Comment by atharwa-24** [comment]
@rkpattnaik780 I had fixed this one

**Comment by utkzas** [comment]
please assign it to me

**Comment by abhinav72610** [comment]
Hey I am new in this community and I am participating in OSH can I take this up?

**Comment by rkpattnaik780** [comment]
Assigning to @atharwa-24 as I can see most people already have an issue assigned to them. @utkzas since it was a first come first serve, I can't assign it to you. Please fell free to browse through other issues. :)

**Comment by atharwa-24** [comment]
@rkpattnaik780 review it once

**Comment by codermind-divya** [comment]
Can I work on this issue?

**Comment by pallavisavant** [comment]
is this available ,can i take this up
