### ISSUE TITLE
Add badges to the Readme File for codecov

### ISSUE THREAD

**Issue by satya7289** [anitab-org/vms#1062]
## Description
Add badges to the Readme File for codecov after this [PR.](https://github.com/anitab-org/vms/pull/983) & update the titile of the Readme file to `Volunteer Management System(VMS)`

## Definition of Done
- [x] Approval by 1 mentor.

## Estimation
1 hours

**Comment by gayathri-venu** [comment]
I would like to work on this issue please assign it to me.

**Comment by Aaishpra** [comment]
can i work on this @satya7289

**Comment by aniketrb-github** [comment]
@satya7289 Can you please assign me this. Thanks. (I'm not an OSH participant but a first-time open source contributor).

**Comment by Aditiwebd** [comment]
I want to work on this issue for OSH

**Comment by satya7289** [comment]
The aim of this program is to make a contributor more comfortable with the open-source contribution. 
Therefore I am assigning this issue to @aniketrb-github. Hope this issue will kickstart your open source contribution, also I encourage you to take part in the Open Source Hack.
@gayathri-venu @Aaishpra @Aditiwebd please look another issue, there are many issues you all can take up.

**Comment by aniketrb-github** [comment]
@satya7289 Thank you for the assignment. I have forked `vms` & have created a new branch for the code fix of this issue.
I believe I have to wait until the mentioned [PR#983](https://github.com/anitab-org/vms/pull/983) is resolved, after which I would be able to raise a PR for #1062 right?

**Comment by satya7289** [comment]
You can open a PR for this @aniketrb-github

**Comment by abhi5459** [comment]
Can you please assign this work to me

**Comment by satya7289** [comment]
Sorry @abhi5459, please look other issues as this is being assigned.
