### ISSUE TITLE
Country, State & City field must be a dropdown in Volunteer Signup 

### ISSUE THREAD

**Issue by decon-harsh** [anitab-org/vms#1080]
Country, State &City field must be a dropdown in Volunteer Signup .

## Mocks
![Screenshot from 2020-09-02 19-36-19](https://user-images.githubusercontent.com/58214248/91994038-be5c2600-ed53-11ea-9855-3231155dce66.png)

## Type 
- User Interface

## Acceptance Criteria
- [X] Form gets modified 

## Definition of Done
- [X] Approval by 1 mentor.

## Estimation
1 hour

**Comment by decon-harsh** [comment]
Kindly review this issue and Let me know if i can work on this?

**Comment by satya7289** [comment]
Already there is a dropdown for country, city, and state. @decon-harsh

**Comment by decon-harsh** [comment]
There is but only in admin signup i guess!

**Comment by sreelekha901** [comment]
Can I work on this issue?

**Comment by decon-harsh** [comment]
Is this already fixed and not yet merged, cause I can still see this issue on my local @satya7289 ? Let me know , in that case i have to close this issue!

**Comment by psingh587** [comment]
Yes, in my local theres no drop down for country, city and state. I was wondering about it till I saw you raised the issue. The dropdown is just there in admin signup. But in live vms, it is there in both.

**Comment by satya7289** [comment]
> Yes, in my local theres no drop down for country, city and state. I was wondering about it till I saw you raised the issue. The dropdown is just there in admin signup. But in live vms, it is there in both.

Have you migrate cities light??
