### ISSUE TITLE
Setup and run

### ISSUE THREAD

**Issue by jatinjain001** [anitab-org/vms#1114]
I think in readme.md file there should have instructions for setup the project on local machine without using doctor ,

**Comment by ankit-saraf** [comment]
@jatinjain001 I think we already have a link to the installation guide in our readme.md file
https://github.com/anitab-org/vms/blob/develop/aut_docs/Installation_Setup.md

**Comment by sanchibansal340** [comment]
@jatinjain001 I am closing this issue as we already have detailed installations guides.
