### ISSUE TITLE
Readme for Open Source Hack

### ISSUE THREAD

**Issue by sharur7** [anitab-org/vms#1125]
Many of us are contributing to Open Source Hack. A readme file containing information on OSH, rules, and guidelines would be great. It would not only be useful for the current contributors but also would be useful for the next batch. This project is a part of OSH. The next batch can take reference from this project to contribute to the next OSH.

**Comment by sharur7** [comment]
Please assign this issue to me

**Comment by sanchibansal340** [comment]
@sharur7 I guess the [website](https://anitab-org.github.io/events/open-source-hack/) has all the information about the OSH program :)
Thank you for closing this issue
