### ISSUE TITLE
Bug: Email Confirmation link is not correct

### ISSUE THREAD

**Issue by KapilBansal320** [anitab-org/vms#1127]
## Description
While Registering as a user I got confirmation link as `http://localhost:8000/registration/signup/activate/b'MQ'/5k5-ca2fd8dd2dfc4a2e61c5/` but it should be `http://localhost:8000/registration/signup/activate/MQ/5k5-ca2fd8dd2dfc4a2e61c5/` instead.

## Screenshot
![11](https://user-images.githubusercontent.com/42766576/93995707-fbde2d00-fdae-11ea-986a-16fbee33c9be.png)

Going to the link gives this error:
![12](https://user-images.githubusercontent.com/42766576/93995754-0a2c4900-fdaf-11ea-8023-d698342f42e4.png)

## Expected Behaviour
![13](https://user-images.githubusercontent.com/42766576/93995878-2cbe6200-fdaf-11ea-9a76-d3c23093e950.png)

Reached by changing the URL as stated above.

## Estimated Time
1 hour to complete

**Comment by KapilBansal320** [comment]
@SanketDG @atharwa-24 @isabelcosta @gaurivn Please add this issue in bug and quality assurance category.

**Comment by sanchibansal340** [comment]
@KapilBansal320 I guess this is a similar issue to https://github.com/anitab-org/vms/issues/1061
Will be closing this for now
