### ISSUE TITLE
blog: OSH Experience

### ISSUE THREAD

**Issue by keshakaneria** [anitab-org/vms#1142]
## Description
We need a blog about the OSH experience for the VMS repo including problems faced by a newcomer which may serve as an intro to VMS repo for prospective contributors.

Write a blog on Medium and share the link in a document called outreach-work.md in the “/docs” folder of VMS. So you need to create a post and add a new line to this document.

Mention AnitaB.org as a publication while publishing the blog/article (called: story on medium).

### Update [Required]
- [ ] [Submit Blog. Add line to outreach-work.md]
### Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.
## Estimation
[1 Hour] hours

**Comment by decon-harsh** [comment]
I will write a blog today itself . Thank you @keshakaneria

**Comment by keshakaneria** [comment]
Great enthusiasm! 🥳 Go for it!

**Comment by ashwinijha6** [comment]
@keshakaneria can more than one person be assigned to this I too want to write a blog on OSH Experience?

**Comment by keshakaneria** [comment]
> @keshakaneria can more than one person be assigned to this I too want to write a blog on OSH Experience?

Sure you can too write one

**Comment by decon-harsh** [comment]
Hey, @keshakaneria I wrote the blog but for adding publication I guess one requires editor permissions.

**Comment by ashwinijha6** [comment]
@keshakaneria could u pls review my pull request
