### ISSUE TITLE
Admin account activation URL is not working

### ISSUE THREAD

**Issue by tarunesh1234** [anitab-org/vms#1163]
![image](https://user-images.githubusercontent.com/32979497/98257263-794bae80-1fa5-11eb-8b5c-22f348db4849.png)

**Comment by devkapilbansal** [comment]
@tarunesh1234 thanks for opening this. But there is already an issuee opened for this and a pull request linked.

**Comment by tarunesh1234** [comment]
Thanks @devkapilbansal
