### ISSUE TITLE
Migrate to Python 3.6 and Django 2.0

### ISSUE THREAD

**Issue by tapaswenipathak** [anitab-org/vms#457]
with all other depdencies to latest compatible version.

**Comment by tonythomas01** [comment]
Yes. I see the need for it here. Probably even to django-rest (in case there are some APIs exposed) - but before that I would say - there should be a pep8 cleanup run for the entire project folder. Things are quite messy in there when you open it up in - say pycharm.

**Comment by joanasouza** [comment]
Hey @tapasweni-pathak @tonythomas01 I would like to work on this issue :)

**Comment by arpitn30** [comment]
I think this should be divided into sub-issues since porting the entire project to Python 3 is a huge task.

**Comment by tonythomas01** [comment]
This is a shame we are on django 1.7.4. I will keep on putting up issues, that would eventually lead to: 
```
1. Shift to python 3.x 
2. Shift to proper CBV. 
```
I can tag them with `python-3.x` so that bugs related to that are separate

**Comment by anjali-dhanuka** [comment]
I am taking up the issue if none is working on it.

**Comment by anjali-dhanuka** [comment]
@tapasweni-pathak 
Python packages stated in the requirements file are not compatible with django 2.0.

**Comment by tapasweni-pathak** [comment]
>@tapasweni-pathak
Python packages stated in the requirements file are not compatible with django 2.0.

Can you please list them down w/ a new issue and we can look into it together?

**Comment by sammy1997** [comment]
This issue conflicts with #557 . @tapasweni-pathak @tonythomas01 @prachi1210 @m-murad

**Comment by anjali-dhanuka** [comment]
@sammy1997 The issue corresponds to Django 1.11 and the other one 2.0. So how do u feel that they are causing conflicts?

**Comment by sammy1997** [comment]
@anjali-dhanuka What I mean is, we shouldn't have 2 issues aiming at 2 django versions. What we can do is, close this and open it later. Maybe the mentors can add an open later tag as well.

**Comment by anjali-dhanuka** [comment]
Yeah we can do that. It may be opened after django 2.0 version gets released. But u can't say that they are conflicting issues. We can always port to Django 2.0 even after we port to Django 1.11.

**Comment by Monal5031** [comment]
@ayushgarg1804 We didn't discuss much, I asked @naman1901 if this could be a part of my GSoC project (Infra and automation) as an stretch goal. But he suggested that I should discuss it with admins first about this.
But as you pointed out as this is a part of @anjali-dhanuka 's proposal so I guess this can't be added in my goals, but I'm really willing to help in this if you want my help :smile:

**Comment by anjali-dhanuka** [comment]
@ayushgarg1804 It is a part of my stretch goals in the proposal and we discussed that if the django-braces too gets released till the end of gsoc period, we can work on it as cities-light has already been relaesed.

**Comment by Fenn-CS** [comment]
Has anyone tried to run the upgrades in an isolated environment? This can be done then we update the requirements docs files then run all tests just to have  an idea of how complex the work is.

**Comment by Monal5031** [comment]
Yes @Fenn-CS I have done that in virtualenv and it is doable I guess in maybe 1-2 weeks.

**Comment by ayushgarg1804** [comment]
@Monal5031 How will you tackle django-braces incompatibility?

**Comment by Monal5031** [comment]
I found a similar issue in issues of django-braces https://github.com/brack3t/django-braces/issues/233 also a related PR to it, I was thinking to give it a try not sure if it'll work though.

**Comment by satya7289** [comment]
I want to work on this issue.

**Comment by Harirai** [comment]
@satya7289  Sure!
