### ISSUE TITLE
Add guidelines for volunteer reviewers

### ISSUE THREAD

**Issue by tapaswenipathak** [anitab-org/vms#593]
Anyone on GitHub can review code. Super grateful and happy to have reviews for VMS. Currently VMS does not have rules/guidelines and other info if someone want to volunteer. It would be useful to add good to know points needed before approving a pull request, to make sure contributors don't get confused after receiving a approval that their change is not required/planned.

cc @systers/systers-vms @systers/systers-vms-admin.

**Comment by willingc** [comment]
Excellent idea. Thanks @tapasweni-pathak.

**Comment by anjali-dhanuka** [comment]
@tapasweni-pathak Are u still on this?

**Comment by tapasweni-pathak** [comment]
@anjali-dhanuka sure, I'll PR. :)

**Comment by abha224** [comment]
Closing this as the contributing guidelines have been added in the repo.
