### ISSUE TITLE
Client side validation for forms

### ISSUE THREAD

**Issue by anjali-dhanuka** [anitab-org/vms#669]
## Description
As a user, I need client side validation along with server side validation for forms so that I can give a more instant response to the user and make the process more user-friendly.

## Mocks
![image](https://user-images.githubusercontent.com/22369767/38911292-c18ac4cc-42eb-11e8-9bcf-d0b1e68aa818.png)

## Acceptance Criteria
- [ ] Built in form validation
- [ ] Additional validations 

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 day

**Comment by anjali-dhanuka** [comment]
@tapasweni-pathak @m-murad @abhishekarya286 @ramitsahwney27 @prachi1210 @kamsuri @sammy1997  Please review the issue.

**Comment by m-murad** [comment]
We should have client-side validation in addition to backend validation.
Backend validation will be later used by Android or iOS clients.

**Comment by kamsuri** [comment]
It will be a good enhancement. Go ahead and submit a PR for the same.

**Comment by anjali-dhanuka** [comment]
Yeah @kamsuri I'll submit the PR as soon as possible.

**Comment by anshulahuja98** [comment]
Can someone brief me about which all forms need this kind of frontend validation, so that i can start working on it...?

**Comment by Monal5031** [comment]
Ping @anjali-dhanuka

**Comment by anjali-dhanuka** [comment]
@anshulahuja98 All the forms out there be it sign up, create form, edit form noone has frontend validation, so it needs to be applied to all of them.

**Comment by anshulahuja98** [comment]
So should I work on a PR by PR basis for each form..

**Comment by anjali-dhanuka** [comment]
@anshulahuja98 It will be better if you use some bootstrap form validations. Besides making these required fields, we need some other validations as well. So I think it will be better.

**Comment by anshulahuja98** [comment]
I have added some regex validation in email and phone number too, and for password fields, i don't  think that we can validate that at frontend because it is handled by django validators.
Can you mention an example of field where I should use bootstrap validation?
