### ISSUE TITLE
Change Travis.yml after porting to django 2.0

### ISSUE THREAD

**Issue by abhishekarya286** [anitab-org/vms#684]
## Description
In travis.yml makemigrations is run for individual apps initially for porting to django 2.0. After porting is done, this needs to be changed.

### Update [Required]
- [ ] Update Travis.yml

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentors.

## Estimation
10 minutes.

**Comment by satya7289** [comment]
Closing this issue, as this issue is no longer exits. Fixed in [PR](https://github.com/anitab-org/vms/pull/972)
