### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/.../vms/vms/srv/MyResume.pdf'

### ISSUE THREAD

**Issue by Monal5031** [anitab-org/vms#744]
## Description
As a developer,
I need to delete the temporary dummy resume which are downloaded during tests and uploaded to `srv/` dir

## Log
Refer this [https://travis-ci.org/systers/vms/builds/396031860#L926](build)
```
======================================================================
ERROR: test_delete_volunteer_resume (volunteer.tests.test_services.VolunteerMethodTests)
Tests delete_volunteer_resume(volunteer_id)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/systers/vms/vms/volunteer/tests/test_services.py", line 45, in test_delete_volunteer_resume
    self.assertTrue(delete_volunteer_resume(self.v1.id))
  File "/home/travis/build/systers/vms/vms/volunteer/services.py", line 38, in delete_volunteer_resume
    volunteer.resume_file.delete()
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/django/db/models/fields/files.py", line 113, in delete
    self.storage.delete(self.name)
  File "/home/travis/virtualenv/python3.6.5/lib/python3.6/site-packages/django/core/files/storage.py", line 386, in delete
    os.remove(name)
PermissionError: [Errno 13] Permission denied: '/home/travis/build/systers/vms/vms/srv/MyResume.pdf'
```

### Update [Required]
- [ ] Update permissions for srv dir

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentor.

## Estimation
10 mins

**Comment by anjali-dhanuka** [comment]
@Monal5031 The link you mentioned is giving 404

**Comment by Monal5031** [comment]
Oh sorry my bad updated it now. I had restarted the build to the previous link got deleted.

**Comment by ayushgarg1804** [comment]
Still giving 404

**Comment by Monal5031** [comment]
@ayushgarg1804 @anjali-dhanuka wierd, can you please check the travis log of volunteer app PR?
https://travis-ci.org/systers/vms/builds/396031860?utm_source=github_status&utm_medium=notification
You can also check it locally, by uploading a resume and try to access it via code or terminal.

**Comment by ayushgarg1804** [comment]
So yeah, according to logs permissions need to be modified. Also do you think it will be beneficial moving to django collectstatic for managing files?

**Comment by Monal5031** [comment]
I haven't used collecstatic before so not sure, but resume is a user-uploaded file and saved in media root and it won't be collected by the collectstatic command? Is there any workaround you have in mind or am I getting this wrong?

**Comment by ayushgarg1804** [comment]
Yeah, it won't be collected by collectstatic

**Comment by muskan6769** [comment]
@Monal5031 @ayushgarg1804 I think this issue is also solved along with issue #776 because that was also because of the same problem.

**Comment by Monal5031** [comment]
True @muskan6769 this will be solved by changing the permissions

**Comment by abha224** [comment]
Closing this issue, as the PR corresponding to this issue ( PR #885 )  is already merged.
