### ISSUE TITLE
Configure codacy

### ISSUE THREAD

**Issue by Monal5031** [anitab-org/vms#783]
## Description
Since we have discussed and agreed to follow good practice of capturing return values even if it is not being used, codacy has pointed out a lot of comments on PRs. Thus we need to configure codacy to ignore this check and stop commenting.
OR
we can configure codacy to have regex check to ignore variables named as `unused_<name>`.

In Either case we have to configure codacy, you can look into https://blog.codacy.com/configuring-codacy-use-your-own-conventions-9272bee5dcdb for more details.

## Mocks
N/A

### Update [Required]
- [ ] Configure codacy to ignore the unused variable check.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentor.

## Estimation
Not sure.

**Comment by sanjana11147** [comment]
Hii @Monal5031 I think I have found the solution to this. I'll try to fix it.

**Comment by sanjana11147** [comment]
I have configured codacy to ignore unused variable checks in my forked project. However, I am not sure how to make a pull request regarding the same as there is no change in the code. @Monal5031

**Comment by satya7289** [comment]
I want to work on this issue.

**Comment by abha224** [comment]
@satya7289 go ahead. I will assign this to you :)

**Comment by yashshah2820** [comment]
ping @satya7289

**Comment by gaurivn** [comment]
Codacy is not needed as CodeCov has been implemented [here](https://github.com/anitab-org/vms/pull/983) and we don't need two quality assurance checks.
