### ISSUE TITLE
Configure django-decouple instead of environment variables

### ISSUE THREAD

**Issue by anshulahuja98** [anitab-org/vms#873]
## Description
As a Member,
I need  to configure django-decouple
so that I can eliminate the hassle of environment variables.

## Mocks
Generally django uses environment variables to set various secrets in settings.py of the project like Database creds, Secret Keys, Emailing ID details, allowed hosts, debug status.
Using environment variables is usually a hassle and is prone to error.
Django decouple takes the settings parameters from a .env file, hence even developers don't need to export environment variables to work and can simply use an example .env file.
Similarly even on the production server, this will simplify things, making it faster to deploy.
 [Read More](https://pypi.org/project/python-decouple/)
[Read More](https://medium.com/@nithinkvijayan/https-medium-com-nithinkvijayan-separating-django-application-config-and-secrets-from-code-python-decouple-e0787d2bcc2a)

### Update [Required]
- Add django-decouple to requirements.txt
- Make all fields in settings.py dynamic with django-decouple
- modify travis.yml accordingly

### Enhancement to Update [Optional]
- [ ]  Write tests

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentor.

## Estimation
1 hours

**Comment by Monal5031** [comment]
Mention all the environment vars you needed to configure and also a short summary of what decouple will do, will make it easier for maintainers to approve issue.

**Comment by anshulahuja98** [comment]
Generally django uses environment variables to set various secrets in settings.py of the project like Database creds, Secret Keys, Emailing ID details, allowed hosts, debug status.
Using environment variables is usually a hassle and is prone to error.
Django decouple takes the settings parameters from a .env file, hence even developers don't need to export environment variables to work and can simply use an example .env file.
Similarly even on the production server, this will simplify things, making it faster to deploy.
 [Read More](https://pypi.org/project/python-decouple/)
[Read More](https://medium.com/@nithinkvijayan/https-medium-com-nithinkvijayan-separating-django-application-config-and-secrets-from-code-python-decouple-e0787d2bcc2a)

**Comment by Monal5031** [comment]
Great! Sounds like a good move but we'll have to wait for admins or maintainers to approve it since it will be dealing on production level too.

**Comment by letmerecall** [comment]
Hi, Can I work on this issue?

**Comment by abhishekspeer** [comment]
Hi there, can I start working on this issue if it is still available? @Monal5031

**Comment by Monal5031** [comment]
Yeah this will be a good move but we'd need to document an example config too.
@abhishekarya286 @letmerecall Since @anshulahuja98 First asked to work on this issue I guess its fair to allow him to complete this issue.

**Comment by anshulahuja98** [comment]
Hey, has this issue been approved now?

**Comment by Monal5031** [comment]
Yeah I just approved it in above comment @anshulahuja98 GFI :+1:

**Comment by anshulahuja98** [comment]
https://github.com/systers/vms/blob/7ca01e87bbc35708af6bc6d2bfe62b2ee70bcec1/vms/vms/settings.py#L124

I can only see the debug settings for email credentials, and that too has been repeated twice in line 124 and 138

Can anyone explain this?

**Comment by anshulahuja98** [comment]
Also how can I update the requirements in the docker image of vms?

**Comment by anaghamittal** [comment]
@Monal5031 @sammy1997 , Can I work on this issue?

**Comment by Monal5031** [comment]
GFI @anaghamittal

**Comment by Monal5031** [comment]
ping @anaghamittal

**Comment by anaghamittal** [comment]
@Monal5031 I am working on this. Just need some more time.

**Comment by abha224** [comment]
@yashshah2820 Pls do ask to be assigned to work on the issue before sending a pr.

**Comment by yashshah2820** [comment]
@abha224 the issue was assigned to me in the vms session :)

**Comment by abha224** [comment]
@yashshah2820 Yes im aware. However, since the session was amongst us, we can't ignore the guidelines for making a pr and it requires you to comment on the issue first. I hope you can understand my intention for asking you to comment on it. :sweat_smile:

**Comment by yashshah2820** [comment]
@abha224 Yes I understand 👍

**Comment by yashshah2820** [comment]
Please review the PR as all the changes have been done
