### ISSUE TITLE
Update admin page title and header

### ISSUE THREAD

**Issue by anshulahuja98** [anitab-org/vms#874]
## Description
As a contributer,
I need update the title and header on admin page
so that I can make the title and header more relevant

## Mocks
# Current
![image](https://user-images.githubusercontent.com/36476228/45913586-df6f2900-be52-11e8-8982-c018e6b70dd2.png)
![image](https://user-images.githubusercontent.com/36476228/45913591-04fc3280-be53-11e8-8b0f-c02483e6b1ae.png)
# Expected
![vms_2](https://user-images.githubusercontent.com/36476228/45913624-9e2b4900-be53-11e8-8486-4f8df274aa87.png)
![vms_1](https://user-images.githubusercontent.com/36476228/45913623-9e2b4900-be53-11e8-89d2-64c8f4bb14f2.png)

### Update [Required]
- [x] Updated title
- [x] Update Header

## Definition of Done
- [x] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by Monal5031** [comment]
Read the issue description first 😛 It needs a approval of any maintainer first.

**Comment by tonythomas01** [comment]
-1 Django administration panel is strictly for administrative purposes (from an operations PoV). 

Hacking around will cost us something later.

**Comment by anshulahuja98** [comment]
@tonythomas01 it's just the page title and headers, i don't think that this could harm in any way!
I personally use this in my django projects.

**Comment by aayush-05** [comment]
This doesn't good enough to be worked on; admin panel would be used mainly by the maintainers. So adding specific header isn't required. Can we get it closed @Monal5031 
Also https://github.com/systers/vms/pull/875 can be closed then.
