### ISSUE TITLE
Define home url only once in urls.py

### ISSUE THREAD

**Issue by Tlazypanda** [anitab-org/vms#879]
## Description
The following command throws a warning because the url home is defined twice in the urls.py file in the main directory.

## Mocks
![image](https://user-images.githubusercontent.com/33183263/48302123-599c5f80-e51e-11e8-8ec4-6344bc198b25.png)
![image](https://user-images.githubusercontent.com/33183263/48302151-a08a5500-e51e-11e8-8174-cbe90935c448.png)

### Update [Required]
- [ ] Code should be changed so that it is only defined once in urls.py

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by Monal5031** [comment]
GFI @Tlazypanda 
IMO the appropriate solution here would be to use URL redirect, please look into that and update the issue accordingly.

**Comment by muskan6769** [comment]
@Monal Can I work on this issue?

**Comment by Monal5031** [comment]
@muskan6769 sorry but there is already an open and active PR for this issue, please look into some other issue and ping me there :)

**Comment by aayush-05** [comment]
@Monal5031 I was looking into this issue, and got this error. Do you know why even the current implementation is not working (even though it is throwing an error)
![image](https://user-images.githubusercontent.com/47032027/74045757-562ea700-49f3-11ea-8f9e-3b69193ca032.png)

**Comment by aayush-05** [comment]
@anjali-dhanuka I was looking into this issue, and got this error. Do you know why even the current implementation is not working (even though it is throwing an error)
![image](https://user-images.githubusercontent.com/47032027/74045757-562ea700-49f3-11ea-8f9e-3b69193ca032.png)

**Comment by cristomathew** [comment]
is this still open?

**Comment by yashshah2820** [comment]
@Monal5031 can I work on this issue

**Comment by Monal5031** [comment]
@yashshah2820 Assigned, GFI 👍

**Comment by yashshah2820** [comment]
on it
