### ISSUE TITLE
Texts overflowing to the left in profile.html

### ISSUE THREAD

**Issue by Tlazypanda** [anitab-org/vms#886]
## Description
In profile.html , the name is not completely visible since a part of it is overflowing to the left.

## Mocks
![screenshot from 2018-12-10 18-55-21](https://user-images.githubusercontent.com/33183263/49735433-34ca1200-fcad-11e8-8fcb-f2373860b8ab.png)

### Update [Required]
- [X] Identify css element causing the problem and removing the error.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by imashwani** [comment]
i have soled the issue should i make a pull request?
After results: The user name doesnot overflows anymore
![screenshot_2018-12-11 volunteer management system 1](https://user-images.githubusercontent.com/20511163/49761877-39fb8100-fcee-11e8-94e7-53eb53481335.png)

**Comment by Tlazypanda** [comment]
Actually you have to first wait for the issue to get approved and you can make a pr only if you are assigned the issue 😅

**Comment by Monal5031** [comment]
Valid issue :+1: Comment down if you want to work on it.

**Comment by Tlazypanda** [comment]
I would like to work on this 😅

**Comment by Monal5031** [comment]
GFI

**Comment by 01shobitha** [comment]
Shall I work on this issue :smile:  ?

**Comment by Niharika-Arora** [comment]
Hi! I'd like to work on this issue.

**Comment by kjain0073** [comment]
Hi! I'd love to work on this issue

**Comment by Monal5031** [comment]
@kjain0073 ,  @Niharika-Arora Asked first so I'll have to assign it to her. Please let me know if wish to work on any other issue

**Comment by Monal5031** [comment]
Fixed in #944
