### ISSUE TITLE
Overlapping Menu and Systers Logo when resizing the browser

### ISSUE THREAD

**Issue by LordGameleo** [anitab-org/vms#900]
## Description

When running locally, if we resize the browser then Horizontal Menu overlaps on Systers Logo.

## Mocks

![1](https://user-images.githubusercontent.com/40512667/51429007-27029780-1c30-11e9-924b-01b4767d4786.png)

### Update [Required]
- [ ] Adaptive menu which changes when the browser size is less than a specific value
- [ ] Make it consistent for all the pages

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

**Comment by Monal5031** [comment]
Go ahead :+1: @LordGameleo Make sure you include the final screenshots in PR

**Comment by marylicious** [comment]
I'm working on this

**Comment by aayush-05** [comment]
One more thing to be mentioned, that on mobile displays toggling the burger button opens the nav list on top of the Systers logo
![image](https://user-images.githubusercontent.com/47032027/73181483-4da9b700-413d-11ea-81d7-6e1d9a6c49ac.png)

**Comment by cristomathew** [comment]
is it done or can i take this up

**Comment by abha224** [comment]
@cristomathew There is already a pr sent for this issue, could you pls take a look at the other issues to work on?
