### ISSUE TITLE
Signup email not being delivered

### ISSUE THREAD

**Issue by aayush-05** [anitab-org/vms#910]
## Description
The email for verification of the user( email id) isn't being sent on the current deployment. Further the system is allowing user to login in further without performing the verification on the email.

### Update [Required]
- [ ] Work on the authorization to allow only verified users to log in

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
6 hours

**Comment by mrsaicharan1** [comment]
I'll work on this. Would appreciate it if you could assign this to me @Monal5031

**Comment by aayush-05** [comment]
I am not sure but this could be due to the expiration of the email service we are using, but still it shouldn't allow login without getting the user verified via that link.

**Comment by mrsaicharan1** [comment]
@aayush-05 I believe you're right. In that case, it would be better if you could update the issue description. Thanks!

**Comment by viratvasu** [comment]
i can do it if you assign it to me

**Comment by Monal5031** [comment]
Currently the code isn't fully deployed on the link available, and if you try it locally you can see that the verification email is sent on the terminal coz it's still a dev version.

So this issue isn't valid for now
