### ISSUE TITLE
Forgot password email not being sent

### ISSUE THREAD

**Issue by aayush-05** [anitab-org/vms#911]
## Description
The email link to reset password isn't being sent to the email id on current deployment

### Update [Required]
- [ ] Make sure the authorization service is working with reset password functionality

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
 hours

**Comment by Monal5031** [comment]
Same as https://github.com/anitab-org/vms/issues/910#issuecomment-596256385
