### ISSUE TITLE
Improving docker image docker-compose and Dockerfile?

### ISSUE THREAD

**Issue by MarkoShiva** [anitab-org/vms#915]
## Description
As a user ,
I should be able to run docker-compose up,
so that I can I have up and running docker stack without the need to run additional commands.

## Mocks
[INSERT RELEVANT PNG FILE]

### Update [Required]
- [ ] docker-compose.yml
- [ ] Dockerfile
- [ ] README.md

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by jains8844** [comment]
I would like to work on this issue

**Comment by jains8844** [comment]
I have some other issues too regarding the docker implementation which I wish to rectify too

**Comment by Monal5031** [comment]
@MarkoShiva A little more description would help here, exactly what you want to achieve with this issue
@jains8844 Yes please go ahead and post them here or on zulip channel

**Comment by husainattar** [comment]
Hi can I work on this issue?
