### ISSUE TITLE
Improving documentation database setup related

### ISSUE THREAD

**Issue by MarkoShiva** [anitab-org/vms#916]
## Description
As a new to the project developer,
I need to be able to setup development environment outside of vagrant and custom image,
so that I can develop efficiently.

## Mocks
[INSERT RELEVANT PNG FILE]

### Update [Required]
- [ ] update documentation related to steps to setup postgresql database
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by MarkoShiva** [comment]
Well as I saw the documentation referenced in readme file is wrong. It reference to aut_docs instead of to main document about installation which already have settings although its a bit too verbose document.

**Comment by theOpetunde** [comment]
Hello,

I'd love to contribute to this project in any way that I can. Has this issue been solved?

**Comment by aayush-05** [comment]
I would like to work on this issue.

**Comment by Monal5031** [comment]
This is being done in https://github.com/anitab-org/vms/issues/932
