### ISSUE TITLE
New user signup returns PermissionError

### ISSUE THREAD

**Issue by theOpetunde** [anitab-org/vms#919]
## Description
As a new user signing up,
I need to submit the sign-up form 
so that I can have a profile and sign-in.

New users trying to sign-up through this link http://ec2-52-53-177-18.us-west-1.compute.amazonaws.com/en-us/registration/signup_volunteer/ get permission error after filling out all the necessary required details and clicking on the "sign-up" button

## Mocks
![anita borg](https://user-images.githubusercontent.com/60391138/73955370-8860db80-4903-11ea-98b8-943fe51e3f04.PNG)
.

## Acceptance Criteria
User sign-up page is successfully submitted and return a "sign-up successful" page
### Update [Required]
- Go to http://ec2-52-53-177-18.us-west-1.compute.amazonaws.com/en-us/registration/signup_volunteer/

- Click on "Sign up" button at the upper right corner of the webpage

- Fill in the necessary and required details

- Click on the "Sign-up" button at the end of the form

- Return a "sign-up successful" page instead of permission error

## Definition of Done
- Create a "sign-up successful" page/prompt that redirects the user (new volunteer) to the sign-in page and allows user to successfully sign-in
- [ ] Approval by 1 mentor.

**Comment by aayush-05** [comment]
Hey !
Can you check up if this issue still exists for you ? I just signed up with a new account and it went on smoothly.
![image](https://user-images.githubusercontent.com/47032027/74037693-d13c9100-49e4-11ea-9bb5-fa02b03c8251.png)

**Comment by theOpetunde** [comment]
Sure.

I tried it once more like you mentioned and here is a screenshot of the response I got:
![anita](https://user-images.githubusercontent.com/60391138/74045152-90388280-49cc-11ea-9826-12d8f413814b.PNG)


What I noticed though is that when I tried using the signup details I used yesterday, it said "user already exists". And then, when I try and use a new user, it returns this error above.

I used Windows OS and chrome browser for the test. Can that be the issue?

**Comment by cristomathew** [comment]
> Sure.
> 
> I tried it once more like you mentioned and here is a screenshot of the response I got:
> ![anita](https://user-images.githubusercontent.com/60391138/74045152-90388280-49cc-11ea-9826-12d8f413814b.PNG)
> 
> What I noticed though is that when I tried using the signup details I used yesterday, it said "user already exists". And then, when I try and use a new user, it returns this error above.
> 
> I used Windows OS and chrome browser for the test. Can that be the issue?

I tried it out too and found no issues.

**Comment by theOpetunde** [comment]
That could happen. It may be that the browser has some issues
