### ISSUE TITLE
Redundant code and outdated database settings

### ISSUE THREAD

**Issue by aayush-05** [anitab-org/vms#920]
## Description
Their is redundant code in the settings.py file and also the database settings are a bit outdated with respect to the current Django version 1.11

## Mocks
![image](https://user-images.githubusercontent.com/47032027/74104758-f57fa580-4b7d-11ea-9918-ea9e0b833e37.png)
![image](https://user-images.githubusercontent.com/47032027/74104760-f9132c80-4b7d-11ea-8c8d-d621ec30a93d.png)

### Update [Required]
- [ ] Fix the given errors

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by aayush-05** [comment]
Can I work on this issue ?

**Comment by Monal5031** [comment]
I don't understand what you mean by redundant code here? @aayush-05  Can you please explain a little bit more :)

**Comment by aayush-05** [comment]
I was talking about the email configuration to console done for local server being copied twice.
![image](https://user-images.githubusercontent.com/47032027/76184632-a5cee100-61f2-11ea-915e-c3a09d126f34.png)

**Comment by Monal5031** [comment]
Ahh okay, you mentioned DB settings so I got confused with that.

Yeah sure please go ahead and send a PR for those 3 redundant lines

**Comment by Kishan-Dhakan** [comment]
Since it has been 3 days without a PR or an comment, Is it okay if I ask to work on this? Hope I am not overstepping :)

**Comment by Monal5031** [comment]
ping @aayush-05

**Comment by Harirai** [comment]
HI, @aayush-05 may I work on this issue? I'm new to open source, this seems to be easy and good for a newcomer.

**Comment by Harirai** [comment]
@Monal5031 I think @aayush-05  is not active on this issue, can you please assign it to me, if possible?

**Comment by aayush-05** [comment]
Sorry @Monal5031 for missing your messages, just gone through the mail box. You can assign it to @Harirai

**Comment by Monal5031** [comment]
I'm sorry @Harirai but @Kishan-Dhakan asked to be assigned first so I'll have to assign it to him.

**Comment by Kishan-Dhakan** [comment]
Yes @Monal5031

**Comment by Monal5031** [comment]
@Harirai Please let me know if you find any other issue you want to work on
