### ISSUE TITLE
Outdated dependency in requirements.txt

### ISSUE THREAD

**Issue by Kishan-Dhakan** [anitab-org/vms#929]
## Description
The requirements.txt file lists Django 1.11.0, however, this version causes a Syntax error while creating migrations for the database (as written in the 8th step in the installation guide [here]).(https://github.com/anitab-org/vms/blob/develop/aut_docs/Installation_Setup.md). This can be resolved by updating Django version to 1.11.17.

## Mocks
![Screenshot from 2020-03-06 12-54-05](https://user-images.githubusercontent.com/42718091/76061670-0b7c5c80-5faa-11ea-97e5-821428df368d.png)

### Update [Required]
- [ ] Update requirements.txt

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.1 hours

**Comment by Monal5031** [comment]
Sure go ahead @Kishan-Dhakan please send a PR :)
