### ISSUE TITLE
Update Communicate section on README

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/vms#930]
## Description

As a contributor,
I need to know where I can reach out to the community,
so that I can discuss or see discussions of this project.

I would suggest updating "Communicate" section to have link to our Zulip and link to #vms stream.
An example of links that can be useful is on [mentorship-backend README](https://github.com/anitab-org/mentorship-backend/).

### Update [Required]
- [ ] Update "Communicate" section with AnitaB.org Open Source Zulip link and #vms stream link. 

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hour

**Comment by AnweshaSen** [comment]
I would like to work on this issue.

**Comment by isabelcosta** [comment]
Go ahead @AnweshaSen :) I will assign this to you.

**Comment by AnweshaSen** [comment]
Please review my Pull Request.
