### ISSUE TITLE
A Concise Installation Guide and updated Readme.md link

### ISSUE THREAD

**Issue by sammy1997** [anitab-org/vms#932]
## Description
As a developer,
I need know how to set up the Postgres DB,
so that I can migrate the models and run VMS locally.

The DB setup part is missing from the currently linked [installation guide](https://github.com/anitab-org/vms/blob/develop/aut_docs/Installation_Setup.md) and the [other guide](https://github.com/anitab-org/vms/blob/develop/docs/Installation_Guide.md) has too much unnecessary information

### Update [Required]
- [ ] Create a new, concise installtion guide with db setup instructions
- [ ] Update the link to the new guide on the main Readme.md file

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1-2 hours

**Comment by sammy1997** [comment]
@isabelcosta @Monal5031 Can you label this with documentation and first-timer labels?

**Comment by isabelcosta** [comment]
Great issue @sammy1997 I assigned the labels

**Comment by Kishan-Dhakan** [comment]
Can I work on this issue?

**Comment by sammy1997** [comment]
Sure @Kishan-Dhakan go ahead!
