### ISSUE TITLE
Fix error on travis CI so the test suite can be executed

### ISSUE THREAD

**Issue by Monal5031** [anitab-org/vms#934]
## Description
As a contributor,
I need to have my changes tested on travis CI,
so that I can assure that my changes dont break anything in current version of code.

## Mocks
![image](https://user-images.githubusercontent.com/21009189/76171585-01797a00-61b3-11ea-95d4-2b1ce3f73494.png)

### Update [Required]
- [ ] .travis.yml file to fix the build so the test suite can run properly

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by Kishan-Dhakan** [comment]
I would like to take this up :)

**Comment by robotjellyzone** [comment]
Hi @Harirai were you assigned by the @Monal5031 or you are just assigning yourself to the issue. If so, then please don't do that as this is not a good way to use such access levels that you got recently. I hope other contributors will not do this for sure @isabelcosta @mayburgos !!

**Comment by Harirai** [comment]
@robotjellyzone Yes, I was working on the issue, and my mentor knew that I was working on it.
I'm really sorry if I wasn't supposed to do that. 
Kishan (who was already assigned) and I, both were working on the issue. I thought if this would enable both of us to add our commit to the same PR, It will be helpful.

Yes I understand your concern :sweat_smile: , I will first message here or wait for the mentor to assign it to me.
Sorry again. :worried: @Monal5031 @mayburgos
