### ISSUE TITLE
Update references on CONTRIBUTING.md to slack

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/vms#942]
## Description

As a contributor,
I need updated references to communication channels used by the community,
so that I can reach out to the community in the correct channels.

Contributing guidelines has still a reference to Slack channels. It should have a link to Zulip and the appropriate stream. This should minimize confusion from newcomers

### Update [Required]
- [ ] Update CONTRIBUTING.md to have links to Zulip space and stream instead of Slack channel.

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation

30 min

**Comment by Harirai** [comment]
@isabelcosta  I would like to work on this issue, this seems to be a nice one to get started :)

**Comment by isabelcosta** [comment]
Sure @Harirai :)

**Comment by Harirai** [comment]
@isabelcosta  Please review the PR, I hope it didn't mess up in my first PR to the org. XD

**Comment by Harirai** [comment]
@isabelcosta Ma'am I understand you are quite busy this time, please close this issue when you get time. :smile:
