### ISSUE TITLE
updating .gitignore and adding migrations folder to all the the apps 

### ISSUE THREAD

**Issue by yashshah2820** [anitab-org/vms#948]
## Description
As a developer,
I need to update the .gitignore file and add the migrations folder within the apps
so that I can apply migrations to the apps and add files .vscode in gitignore so that this folder can be ignored while staging changes.

## Mocks
![image](https://user-images.githubusercontent.com/42682370/76863070-03170200-6885-11ea-997a-e5f6831f15e6.png)

### Add
- [ ] migrations folder to all the apps

### Update 
- [ ] gitignore

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
10 minutes

**Comment by Monal5031** [comment]
Yup makes sense to have at least __init__.py inside migrations folder

Valid issue :+1:

**Comment by yashshah2820** [comment]
can I work on this issue @Monal5031

**Comment by Kishan-Dhakan** [comment]
@yashshah2820 you have not been assigned this issue.

**Comment by yashshah2820** [comment]
okay, I will do the needful👍

**Comment by hardikkat24** [comment]
Is anybody working on this issue? I would like to work on this.

**Comment by yashshah2820** [comment]
@hardikkat24 you can work on this issue👍

**Comment by hardikkat24** [comment]
@yashshah2820 should i add sublime text files to the gitignore too?

**Comment by yashshah2820** [comment]
@hardikkat24 yes you can 👍

**Comment by hardikkat24** [comment]
i have made the pull request, please review it and tell me if any changes are required.
