### ISSUE TITLE
fix the volunteer sign up page

### ISSUE THREAD

**Issue by abha224** [anitab-org/vms#950]
## Description
When an user tries to sign up as a volunteer , there is an error generated and the form does not load.
## Mocks
![Screenshot from 2020-03-17 20-31-41](https://user-images.githubusercontent.com/39526159/76869546-7ffaa980-688e-11ea-8c37-c1bc38cbff4f.png)

### Update [Required]
- [ ] code has to be updated

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[0.5] hours

**Comment by Monal5031** [comment]
I know the issue is valid @abha224 But please add more description explaining the bug.

Approved :+1: but add more description

**Comment by Niharika-Arora** [comment]
Hi! I'd like to work on this issue.

**Comment by abha224** [comment]
Okay! I have updated the description.

**Comment by raghavdhingra** [comment]
I have solved the issue and made a PR. 
PR id: #957

**Comment by BeKingsman** [comment]
@Monal5031 @sammy1997 Can I work on this issue if it's still available?

**Comment by raghavdhingra** [comment]
@BeKingsman I have fixed the issue already. Thanks for your approach to this issue.

**Comment by raghavdhingra** [comment]
@Monal5031 Could you please assign and review the PR #957

**Comment by Monal5031** [comment]
@raghavdhingra Sorry but 2 people have asked to be assigned before you, if they don't want to work on it then you can send a PR :) I'm sorry but every contributor has to follow the guidelines.

@Niharika-Arora You still wish to work on this issue?

**Comment by raghavdhingra** [comment]
Sure Monal, I understand the Guidelines. If no one wants to work on it then I would send the PR again.

**Comment by raghavdhingra** [comment]
Could you please assign me now @Monal5031 as no one has given the response yet?

**Comment by anaghamittal** [comment]
I have fixed this issue locally on my machine and would now like to work on this if available.

**Comment by poorvakhandare3006** [comment]
@Monal5031 I would like to work on this issue

**Comment by yashshah2820** [comment]
@Niharika-Arora You still wish to work on this issue?

**Comment by yashshah2820** [comment]
@raghavdhingra you can work on this issue 👍

**Comment by raghavdhingra** [comment]
I've made a PR #966 for it
