### ISSUE TITLE
fix serving uploaded docs through media

### ISSUE THREAD

**Issue by yashshah2820** [anitab-org/vms#951]
## Description
As a Member,
I need to add static files path to URL patterns in the vms urls.py,
so that I can serve the uploaded documents.

## Mocks
![image](https://user-images.githubusercontent.com/42682370/76887015-9c571000-68a7-11ea-863b-bf03e6c6f980.png)

## Steps to reproduce
To serve the uploaded media files through URL like 
srv/vms/resume/[pdf_name] 
this URL should be able to view the media files

### Update [Required]
- [ ] vms urls.py file 
- [ ] .gitignore

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
10 minutes

**Comment by Monal5031** [comment]
Valid issue :+1:

**Comment by yashshah2820** [comment]
can I work on this issue @Monal5031

**Comment by krishna0303** [comment]
I would like to work on this issue @Monal5031

**Comment by Kishan-Dhakan** [comment]
@yashshah2820 you have not been assigned this issue.

**Comment by yashshah2820** [comment]
okay, I will do the needful.👍

**Comment by sankha555** [comment]
Hello @yashshah2820 ,
I am interested in working on this issue. Can you please assign it to me if it's still open? Thanks :)

**Comment by yashshah2820** [comment]
Since @krishna0303 asked first so it would be fair to allow him to work on this issue 🙂

**Comment by sankha555** [comment]
Sure, @yashshah2820 . Meanwhile if there are some other issues that you think can be solved, I would be obliged if you can mention those to me. Thanks !

**Comment by yashshah2820** [comment]
@sankha555 you can view all the issues in the Issues section and decide which issue to work on according to you

**Comment by yashshah2820** [comment]
@sankha555 you can work on this issue 👍

**Comment by sankha555** [comment]
Hello @yashshah2820 ,
Sorry for the delayed response, I was a bit occupied with college assignments. I have made a pull request, can you please review it? Thanks!
