### ISSUE TITLE
update the README.md to fix broken link

### ISSUE THREAD

**Issue by Harirai** [anitab-org/vms#953]
## Description
As a contributor,
I need to use the live site,
so that I can suggest enhancements/bugs.

![Screenshot from 2020-03-18 23-06-51](https://user-images.githubusercontent.com/43855822/76989972-37fe8400-696d-11ea-9e63-af9eaaf5b795.png)

` VMS is live ` [here](http://52.8.110.63/)
is not working.

### Update 
- [ ] Fix the link to live website.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
10 min

**Comment by Harirai** [comment]
@Monal5031 Kindly assign me this issue.

**Comment by Monal5031** [comment]
Add more description please

**Comment by Harirai** [comment]
@Monal5031  Sir I have edited it, kindly have a look.

**Comment by owais4321** [comment]
Kindly assign me this issue

**Comment by Harirai** [comment]
As this issue is same as #969,  I'm closing this.
