### ISSUE TITLE
hide sensitive data and setup environment variables

### ISSUE THREAD

**Issue by yashshah2820** [anitab-org/vms#958]
## Description
As a member,
I need to implement python-decouple for environment variables
so that I can hide sensitive data like SECRET_KEY, ALLOWED_HOSTS, database password.

## Mocks
![image](https://user-images.githubusercontent.com/42682370/78386768-ccb6e200-75fb-11ea-8555-4fbf48f20cb6.png)

### Update [Required]
- [ ] settings.py
- [ ] add .env in root
- [ ] update .gitignore

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
30 mins

**Comment by Kishan-Dhakan** [comment]
@Monal5031 @yashshah2820 this issue already exists at #873. Please confirm.

**Comment by yashshah2820** [comment]
okay, removing it.
