### ISSUE TITLE
Complete missing parts and update outdated sections in Readme.md

### ISSUE THREAD

**Issue by Kishan-Dhakan** [anitab-org/vms#969]
## Description
As a Contributor,
I need an up-to-date README tells me everything about the project,
so that I can Contribute accordingly.

## To Do: 
1) Update the Features section, it seems to be written during project inception (2014).
2) Update the GSOC development section, specifically, Developments done in 2018 are missing.
3) Update the support section, it mentions a mailing list from systers.org.
4) Link to contributing guidelines doc in the Contributing Section.

## Mocks
The current feature section:
![Screenshot from 2020-05-11 00-29-42](https://user-images.githubusercontent.com/42718091/81507991-cfa1a280-931e-11ea-8b6c-8695e9b073fd.png)

The Other 3 sections:
![Screenshot from 2020-05-11 00-29-47](https://user-images.githubusercontent.com/42718091/81507992-d16b6600-931e-11ea-8e15-6233f2c8414e.png)

As seen, all the mentioned sections need to be updated.

### Update [Required]
- [ ] [Features section]
- [ ] [GSoC Development section]
- [ ] [Support section]
- [ ] [Contributing section]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3-4 hours

**Comment by gaurivn** [comment]
I would like to work on this issue.

**Comment by gaurivn** [comment]
The mailing list from Systers.org, should it be replaced or can it/support section be removed completely. I'm unable to find a mailing list for AnitaB.org

**Comment by Kishan-Dhakan** [comment]
> The mailing list from Systers.org, should it be replaced or can it/support section be removed completely. I'm unable to find a mailing list for AnitaB.org

If that's the case, you can link the AnitaB.org zulipchat, that should do it :)

**Comment by gaurivn** [comment]
AnitaB.org zulipchat is already mentioned in Communicate. @Kishan-Dhakan, can I repeat the same under Support?
