### ISSUE TITLE
Add a badge to join Zulip chat on README

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/vms#990]
## Description

As a new contributor,
I need know which chat can I join regarding this project,
so that I can discuss this project with the community.

I did something similar in here https://github.com/anitab-org/mentorship-backend/pull/683

## Mocks

![image](https://user-images.githubusercontent.com/11148726/87972855-89578500-cabf-11ea-964d-f2d35b295c84.png)

### Update [Required]
- [ ] Add Zulip chat badge to README with link to Zulip stream dedicated to #vms (link: https://anitab-org.zulipchat.com/#narrow/stream/222539-vms)

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hours

**Comment by saideepesh000** [comment]
Hi @isabelcosta, can I try this, please assign me.

**Comment by isabelcosta** [comment]
@saideepesh000 its assigned to you ;) You can start working on it!
